package Problem045;

/**
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 * Triangle 	  	Tn=n(n+1)/2 	1, 3, 6, 10, 15, ...
 * Pentagonal 	  	Pn=n(3n−1)/2 	1, 5, 12, 22, 35, ...
 * Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
 * <p>
 * It can be verified that T285 = P165 = H143 = 40755.
 * <p>
 * Find the next triangle number that is also pentagonal and hexagonal
 */

public class TriPentaHex {
    public static void main(String[] args) {
        long tri = 285 + 1;
        long penta = 165 + 1;
        long hex = 143 + 1;

        while (true) {
            long triangle = tri * (tri + 1) / 2;
            long pentagon = penta * (penta * 3 - 1) / 2;
            long hexagon = hex * (hex * 2 - 1);

            long ans = Math.min(Math.min(triangle, pentagon), hexagon);

            if (ans == triangle && ans == pentagon && ans == hexagon) {
                System.out.println(ans);
                break;
            }

            if (ans == triangle) tri++;
            if (ans == pentagon) penta++;
            if (ans == hexagon) hex++;
        }
    }
}